import { ApiProperty } from '@nestjs/swagger';
import { AddGroupMemberDto } from './add-group-member.dto';
import { AddGroupMembersBulkDto } from './add-group-members-bulk.dto';
import { AddSubscriberDto } from './add-subscriber.dto';
import { DeleteGroupMemberDto } from './delete-group-member.dto';
import { SubscribeServiceDto } from './subscribe-service.dto';
import { UpdateSubscriptionDto } from './update-subscription.dto';
import { ProvisioningOperation } from '../enums/provisioning-operation.enum';

class ProvisioningCommandResponseBaseDto {
  @ApiProperty({
    description: 'Unique request correlation identifier generated by this API.',
    format: 'uuid',
    example: 'ae9183e8-5974-4183-824b-85f718adbb6d',
  })
  requestId: string;

  @ApiProperty({
    description:
      'Indicates whether the upstream provisioning request was accepted.',
    example: true,
  })
  accepted: boolean;

  @ApiProperty({
    description: 'Timestamp when the provisioning request completed.',
    example: '2026-05-01T09:30:00.000Z',
  })
  processedAt: string;

  @ApiProperty({
    description:
      'HTTP status code returned by the upstream provisioning integration.',
    example: 200,
  })
  providerStatusCode: number;

  @ApiProperty({
    description:
      'Sanitized provider response body returned by the provisioning adapter. Provider-specific secrets are never exposed here.',
    type: 'object',
    additionalProperties: true,
    nullable: true,
    example: {
      successful: true,
      resultCode: '0',
      message: 'Operation succeeded',
    },
  })
  providerResponse: Record<string, unknown> | null;
}

export class AddGroupMemberResponseDto extends ProvisioningCommandResponseBaseDto {
  @ApiProperty({
    enum: ProvisioningOperation,
    example: ProvisioningOperation.ADD_GROUP_MEMBER,
  })
  operation: ProvisioningOperation;

  @ApiProperty({
    description: 'Normalized payload forwarded to the provisioning adapter.',
    type: () => AddGroupMemberDto,
  })
  request: AddGroupMemberDto;
}

export class AddGroupMembersBulkResponseDto extends ProvisioningCommandResponseBaseDto {
  @ApiProperty({
    enum: ProvisioningOperation,
    example: ProvisioningOperation.ADD_GROUP_MEMBERS_BULK,
  })
  operation: ProvisioningOperation;

  @ApiProperty({
    description:
      'Normalized bulk payload forwarded to the provisioning adapter.',
    type: () => AddGroupMembersBulkDto,
  })
  request: AddGroupMembersBulkDto;
}

export class DeleteGroupMemberResponseDto extends ProvisioningCommandResponseBaseDto {
  @ApiProperty({
    enum: ProvisioningOperation,
    example: ProvisioningOperation.DELETE_GROUP_MEMBER,
  })
  operation: ProvisioningOperation;

  @ApiProperty({
    description:
      'Normalized delete payload forwarded to the provisioning adapter.',
    type: () => DeleteGroupMemberDto,
  })
  request: DeleteGroupMemberDto;
}

export class UpdateSubscriptionResponseDto extends ProvisioningCommandResponseBaseDto {
  @ApiProperty({
    enum: ProvisioningOperation,
    example: ProvisioningOperation.UPDATE_SUBSCRIPTION,
  })
  operation: ProvisioningOperation;

  @ApiProperty({
    description:
      'Normalized subscription update payload forwarded to the provisioning adapter.',
    type: () => UpdateSubscriptionDto,
  })
  request: UpdateSubscriptionDto;
}

export class AddSubscriberResponseDto extends ProvisioningCommandResponseBaseDto {
  @ApiProperty({
    enum: ProvisioningOperation,
    example: ProvisioningOperation.ADD_SUBSCRIBER,
  })
  operation: ProvisioningOperation;

  @ApiProperty({
    description:
      'Normalized subscriber payload forwarded to the provisioning adapter.',
    type: () => AddSubscriberDto,
  })
  request: AddSubscriberDto;
}

export class SubscribeServiceResponseDto extends ProvisioningCommandResponseBaseDto {
  @ApiProperty({
    enum: ProvisioningOperation,
    example: ProvisioningOperation.SUBSCRIBE_SERVICE,
  })
  operation: ProvisioningOperation;

  @ApiProperty({
    description:
      'Normalized subscribe-service payload forwarded to the provisioning adapter.',
    type: () => SubscribeServiceDto,
  })
  request: SubscribeServiceDto;
}
