import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import * as crypto from 'node:crypto';

import { AuthChallenge } from '../../../entities/auth-challenge.entity';
import { AuthChallengeType } from '../../../enums/auth-challenge-type.enum';
import { WebauthnCredential } from '../../../entities/webauthn-credential.entity';
import { MfaMethod } from '../../../enums/mfa-method.enum';
import {
  MfaChallenge,
  MfaProvider,
  MfaVerificationResult,
} from '../../../interfaces/mfa-provider.interface';
import { UserService } from 'src/modules/users/services/user.service';
import { WebauthnAuthenticationService } from '../../webauthn/webauthn-authentication.service';

/**
 * Provides WebAuthn-based MFA challenges and verification.
 *
 * This provider delegates WebAuthn protocol details to the dedicated
 * WebAuthn authentication service and only adapts that flow to the
 * shared MFA provider contract.
 */
@Injectable()
export class WebauthnMfaProvider implements MfaProvider {
  readonly method = MfaMethod.WEBAUTHN;

  private readonly challengeTtlMinutes = 5;

  constructor(
    @InjectRepository(AuthChallenge)
    private readonly authChallengeRepo: Repository<AuthChallenge>,
    @InjectRepository(WebauthnCredential)
    private readonly webauthnCredentialRepo: Repository<WebauthnCredential>,
    private readonly usersService: UserService,
    private readonly webauthnAuthenticationService: WebauthnAuthenticationService,
  ) {}

  /**
   * Indicates whether the WebAuthn MFA provider is globally available.
   */
  isAvailable(): boolean {
    return true;
  }

  /**
   * Creates a WebAuthn MFA challenge for a user.
   *
   * The actual browser-facing options are generated by the WebAuthn
   * authentication service and embedded in the MFA challenge metadata.
   */
  async createChallenge(
    userId: string,
    context?: Record<string, unknown>,
  ): Promise<MfaChallenge> {
    const user = await this.usersService.requireById(userId);

    const credentials = await this.webauthnCredentialRepo.find({
      where: {
        userId: user.id,
        isEnabled: true,
      },
      order: {
        isPrimary: 'DESC',
        createdAt: 'ASC',
      },
    });

    if (!credentials.length) {
      throw new NotFoundException(
        'No enabled WebAuthn credentials found for user',
      );
    }

    /**
     * Ask the dedicated WebAuthn auth service to generate assertion options.
     * This service should return a challenge and allowCredentials payload
     * suitable for navigator.credentials.get(...).
     */
    const webauthnOptions =
      await this.webauthnAuthenticationService.beginAuthentication({
        userId: user.id,
      });

    const expiresAt = new Date(
      Date.now() + this.challengeTtlMinutes * 60 * 1000,
    );

    const challenge = this.authChallengeRepo.create({
      userId,
      type: AuthChallengeType.MFA,
      challenge: crypto.randomUUID(),
      expiresAt,
      isUsed: false,
      payload: {
        method: this.method,
        webauthnChallenge: webauthnOptions.challenge,
        allowCredentials: webauthnOptions.allowCredentials ?? [],
        timeout: webauthnOptions.timeout ?? 60000,
        rpId: webauthnOptions.rpId ?? null,
        ...context,
      },
    });

    const saved = await this.authChallengeRepo.save(challenge);

    return {
      challengeId: saved.id,
      method: this.method,
      expiresAt,
      metadata: {
        options: webauthnOptions,
      },
    };
  }

  /**
   * Verifies a WebAuthn MFA challenge using the browser assertion response.
   *
   * Expected response shape should include the assertion payload returned by
   * navigator.credentials.get(...). The dedicated WebAuthn auth service is
   * responsible for cryptographic verification.
   */
  async verifyChallenge(
    userId: string,
    challengeId: string,
    response: Record<string, unknown>,
  ): Promise<MfaVerificationResult> {
    const challenge = await this.authChallengeRepo.findOne({
      where: {
        id: challengeId,
        userId,
        type: AuthChallengeType.MFA,
        isUsed: false,
      },
    });

    if (!challenge) {
      return {
        success: false,
        reason: 'mfa_challenge_not_found',
      };
    }

    if (challenge.expiresAt < new Date()) {
      return {
        success: false,
        reason: 'mfa_challenge_expired',
      };
    }

    const expectedMethod = String(challenge.payload?.method ?? '');
    if (expectedMethod !== this.method) {
      return {
        success: false,
        reason: 'mfa_challenge_method_mismatch',
      };
    }

    /**
     * The browser assertion payload should be passed as-is in `response`.
     * We attach the stored WebAuthn challenge so the verification service can
     * validate that the assertion matches the originally issued challenge.
     */
    const assertion = response.assertion as Record<string, unknown> | undefined;

    if (!assertion) {
      return {
        success: false,
        reason: 'missing_webauthn_assertion',
      };
    }

    const rawChallenge = challenge.payload?.webauthnChallenge;

    if (typeof rawChallenge !== 'string') {
      throw new BadRequestException('Invalid WebAuthn challenge');
    }

    const verification =
      await this.webauthnAuthenticationService.finishAuthentication({
        assertion,
      });

    if (!verification?.success) {
      return {
        success: false,
        reason:
          typeof verification?.reason === 'string'
            ? verification.reason
            : 'webauthn_verification_failed',
      };
    }

    challenge.isUsed = true;
    await this.authChallengeRepo.save(challenge);

    return {
      success: true,
    };
  }
}
