export enum AuthChallengeType {
  MFA = 'MFA',
  WEBAUTHN_REGISTRATION = 'WEBAUTHN_REGISTRATION',
  WEBAUTHN_AUTHENTICATION = 'WEBAUTHN_AUTHENTICATION',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_ACTIVATION = 'ACCOUNT_ACTIVATION',
}
